# ===========================
# Minimal Mistakes Config
# ===========================

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# Site Settings
locale: "en"
title: "Will Kwan"
subtitle: ""
name: "Will Kwan"
description: "A personal portfolio showcasing projects and experiences in Environmental Science and Computer Science."
url: "https://willrkwan.github.io"
baseurl: ""
masthead_title: "Will Kwan"
logo: ""  # optional, leave blank if none
breadcrumbs: false 
words_per_minute: 200
enable_copy_code_button: true
author_profile: true 

copyright: "Will Kwan"
copyright_url: "https://willrkwan.github.io"

# =========================== 
# Footer
# ===========================
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/willrkwan"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/willrkwan"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:willrkwan@gmail.com"
  powered_by: false
  since: "2025"

# ===========================
# Author
# ===========================
author:
  name: "Will Kwan"
  avatar: "/assets/images/bio-photo.jpg"  # optional
  bio: "B.Sc. Environmental Science and Computer Science Student"
  location: "Kelowna, British Columbia"
  # email: "willrkwan@gmail.com"
   links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/willrkwan"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/willrkwan"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:willrkwan@gmail.com"

# ===========================
# Pages & Posts
# ===========================  
include:
  - _pages
exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json

# ===========================
# Markdown & Syntax
# ===========================
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1

# ===========================
# Pagination
# ===========================
paginate: 5
paginate_path: "/page:num/"
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'

# ===========================
# Plugins
# ===========================
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache

# ===========================
# SEO / Search
# ===========================
search: false
search_provider: lunr
algolia:
  powered_by: false
