name: Jekyll site CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      # 3. Install Bundler and dependencies (including Minimal Mistakes)
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4

      # 4. Build the Jekyll site with verbose output
      - name: Build site
        run: bundle exec jekyll build --trace --verbose

      # 5. Deploy to GitHub Pages, forcing a new commit each time
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          keep_files: true
          commit_message: "Deploy site: ${{ github.sha }}"
